from ..const import PROXY_URL_PREFIX,NEED_PROXY


TELEGRAM_BOT_API_URL_PREFIX = "https://api.telegram.org"

if NEED_PROXY and PROXY_URL_PREFIX:
    TELEGRAM_BOT_API_URL_PREFIX = f"{PROXY_URL_PREFIX}/{TELEGRAM_BOT_API_URL_PREFIX}"
