from ..const import LOCATION,PROXY_URL_PREFIX


TELEGRAM_BOT_API_URL_PREFIX = "https://api.telegram.org"

if LOCATION in ["CN",None] and PROXY_URL_PREFIX:
    TELEGRAM_BOT_API_URL_PREFIX = f"{PROXY_URL_PREFIX}/{TELEGRAM_BOT_API_URL_PREFIX}"
