from ..const import LOCATION,PROXY_URL_PREFIX,NEED_PROXY_LOCATION_LIST


TELEGRAM_BOT_API_URL_PREFIX = "https://api.telegram.org"

if LOCATION in NEED_PROXY_LOCATION_LIST and PROXY_URL_PREFIX:
    TELEGRAM_BOT_API_URL_PREFIX = f"{PROXY_URL_PREFIX}/{TELEGRAM_BOT_API_URL_PREFIX}"
